# Simple workflow for deploying static content to GitHub Pages
name: copy to pages

on:
  push:
    branches: ["master"]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
  
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Copy to pages
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch
          git switch pages
          git rm -rf *
          git restore --source ${GITHUB_REF##*/} .
          rm -rf ./github
          git add -A
          git commit -m "copy from main"
          git push
